# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    cd terraform/
    terraform init
  displayName: 'Pre run terraform init'

- task: AzureCLI@2
  displayName: "Terraform Init"
  inputs:
    azureSubscription: ARM_SUBSCRIPTION
    scriptType: bash
    addSpnToEnvironment: true
    scriptLocation: inlineScript
    inlineScript: |
      echo "starting..."
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_TENANT_ID=$tenantId
      cd test/
      go test -timeout 60m
  displayName: 'Run a go test'

